### ISSUE TITLE
Name/logo

### ISSUE THREAD

**Issue by cdtama7** [cdtama7/TeamFour#10]

**Comment by phairowwcire** [comment]
![justclass](https://user-images.githubusercontent.com/55906188/73595574-4d683d80-44e8-11ea-8fad-6e93fc2fc040.jpg)
![classy2](https://user-images.githubusercontent.com/55906188/73595575-4d683d80-44e8-11ea-9aed-6d571df967b2.jpg)

**Comment by phairowwcire** [comment]
![Qourse](https://user-images.githubusercontent.com/55906188/73595937-b00f0880-44eb-11ea-9780-8f127f605598.jpg)

**Comment by phairowwcire** [comment]
![classyrevision](https://user-images.githubusercontent.com/55906188/73597728-2cf6ae00-44fd-11ea-88b3-58b54b35ba8e.jpg)

**Comment by phairowwcire** [comment]
final? revision?
